[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "cargo flash --chip nRF52840_xxAA"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  # "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf"